### ISSUE TITLE
2 CPU offline

### ISSUE THREAD

**Issue by bapstc357** [xmixahlx/debian-packages#1]
2 CPU are offline with either the stable and testing kernels.
[StartupLog.txt](https://github.com/xmixahlx/debian-packages/files/4973177/StartupLog.txt)

**Comment by xmixahlx** [comment]
remove maxcpus=4 in u-boot config.

edit /etc/default/u-boot
sudo u-boot-update

**Comment by bapstc357** [comment]
Sorry, I did not pay attention to this parameter. The same parameter with 5.5 let the 6 CPU online anyway. Thanks for the tip.
